# Generated by Django 5.0.1 on 2024-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_idea_options_alter_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='periodic',
            options={'verbose_name': 'Периодическая задача', 'verbose_name_plural': 'Периодические задачи'},
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
