# Generated by Django 5.0.1 on 2024-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_periodic_next_execution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
