# Generated by Django 4.2.5 on 2024-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_alter_list_content_alter_list_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodic',
            name='next_execution_time',
        ),
        migrations.RemoveField(
            model_name='periodic',
            name='repetition_period',
        ),
        migrations.AddField(
            model_name='periodic',
            name='days_of_week',
            field=models.CharField(choices=[('never', 'Никогда'), ('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='never', max_length=20),
        ),
        migrations.AddField(
            model_name='periodic',
            name='time_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
