# Generated by Django 4.2.5 on 2024-02-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blocks", "0013_category_user_idea_user_list_user_notes_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodic",
            options={
                "verbose_name": "Периодическая задача",
                "verbose_name_plural": "Периодические задачи",
            },
        ),
        migrations.RemoveField(
            model_name="periodic",
            name="days_of_week",
        ),
        migrations.AddField(
            model_name="periodic",
            name="friday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="monday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="saturday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="sunday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="thursday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="tuesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="periodic",
            name="wednesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="idea",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="periodic",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="periodic",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="periodic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
